/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import AccesoADatos.CompraData;
import AccesoADatos.DetalleCompraData;
import AccesoADatos.ProductoData;
import AccesoADatos.ProveedorData;
import Entidades.Proveedor;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Entidades.Producto;
import Entidades.Compra;
import Entidades.DetalleCompra;

/**
 *
 * @author Cristian
 */
public class ListadoCompraProveedor extends javax.swing.JInternalFrame {

    private ProveedorData prove = new ProveedorData();
    private CompraData comp = new CompraData();
    private ProductoData prod = new ProductoData();
    private DetalleCompraData det = new DetalleCompraData();
    private List<Compra> fuenteC= comp.listarCompras();
    private List<Producto> fuenteP= prod.listarProductos();
    private List<Proveedor> fuente= prove.listarProveedor();
    DefaultTableModel tab = new DefaultTableModel();
    DefaultTableModel tab2 = new DefaultTableModel();
    
    
    
    public ListadoCompraProveedor() {
        initComponents();
        cargarProveedor();
        String ads[] = {"Identificador", "Fecha", "Estado"};
        String ids[] = {"Identificador", "Nombre", "Descripción", "Precio", "Stock"};
        tab.setColumnIdentifiers(ads);
        tab2.setColumnIdentifiers(ids);
        jTProducto.setModel(tab2);
        tab.setColumnIdentifiers(ads);
        jTCompra.setModel(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCProveedores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCompra = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Seleccione un Proveedor :");

        jCProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProveedoresActionPerformed(evt);
            }
        });

        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProducto);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Listado compra por Proveedor");

        jTCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTCompra);

        jLabel3.setText("Tabla de compras");

        jLabel4.setText("Tabla deproductos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jCProveedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBSalir)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProveedoresActionPerformed
        // TODO add your handling code here:
        int id = ((Proveedor) jCProveedores.getSelectedItem()).getIdProveedor();
        borrarFilas();
        for (Compra tabMos : fuenteC) {
            if (tabMos.getProveedor().getIdProveedor() == id) {
                tab.addRow(new Object[]{tabMos.getIdCompra(), tabMos.getFecha(), tabMos.isEstado()});
            }
        }

    }//GEN-LAST:event_jCProveedoresActionPerformed

    private void jTCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCompraMouseClicked
        // TODO add your handling code here:
     int filaSeleccionada = jTCompra.getSelectedRow();
    borrarFilas2();

    if (filaSeleccionada >= 0) {
        // ID de la compra seleccionada
        int idCompraSeleccionada = (int) jTCompra.getValueAt(filaSeleccionada, 0);

        // La compra coincide con el ID
         Compra compraSeleccionada = null;
        for (Compra compra : fuenteC) {
            if (compra.getIdCompra() == idCompraSeleccionada) {
                compraSeleccionada = compra;
                break;
            }
        }

        // Verificar si la compra seleccionada no es nula
        if (compraSeleccionada != null) {
            // Obtiene los detalles de compra
            List<DetalleCompra> detallesCompra = det.listarDetallesPorCompra(compraSeleccionada);

            // Llena la tabla jTProducto con los productos
            for (DetalleCompra detalle : detallesCompra) {
                Producto producto = detalle.getProducto();
                tab2.addRow(new Object[]{
                    producto.getIdProducto(),
                    producto.getNombreProducto(),
                    producto.getDescripcion(),
                    producto.getPrecioActual(),
                    producto.getStock()
                });
            }
        }
    }
    }//GEN-LAST:event_jTCompraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Proveedor> jCProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCompra;
    private javax.swing.JTable jTProducto;
    // End of variables declaration//GEN-END:variables
    private void borrarFilas() {
        int indice = tab.getRowCount() - 1;
        
        for (int i = indice; i >= 0; i--) {
            tab.removeRow(i);
        }
    }
     private void borrarFilas2() {
        int indice = tab2.getRowCount() - 1;
        
        for (int i = indice; i >= 0; i--) {
            tab2.removeRow(i);
        }
    }
    
    private void cargarProveedor() {
        for (Proveedor item : fuente) {
            jCProveedores.addItem(item);
        }
    }




}
