/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import AccesoADatos.ProductoData;
import Entidades.Producto;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco
 */
public class ListarProductosFechas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarProductosFechas
     */
    DefaultTableModel tab = new DefaultTableModel();

    public ListarProductosFechas() {
        initComponents();
        String ids[] = {"Nombre Producto", "Descripcion", "Precio Actual", "Stock", "Stock Minimo"};
        tab.setColumnIdentifiers(ids);
        jTProductos.setModel(tab);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDCIngreso = new com.toedter.calendar.JDateChooser();
        jDCEgreso = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jBBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRFechaEspecifica = new javax.swing.JRadioButton();
        jREntreFechas = new javax.swing.JRadioButton();

        setClosable(true);

        jDCIngreso.setEnabled(false);

        jDCEgreso.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Lista por fecha");

        jLabel2.setText("Fecha Inicial");

        jLabel3.setText("Fecha Final");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRFechaEspecifica.setText("Busqueda por fecha especifica");
        jRFechaEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFechaEspecificaActionPerformed(evt);
            }
        });

        jREntreFechas.setText("Busqueda entre fechas");
        jREntreFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREntreFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDCIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jRFechaEspecifica)
                                    .addComponent(jREntreFechas))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDCEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRFechaEspecifica)
                .addGap(15, 15, 15)
                .addComponent(jREntreFechas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        List<Producto> productos = new ArrayList<>();
        ProductoData pd = new ProductoData();
        if (jRFechaEspecifica.isSelected()) {
            java.util.Date fecha1 = jDCIngreso.getDate();
            LocalDate fechaComp1 = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            productos = pd.buscarProductoPorFechas(fechaComp1, fechaComp1);
        }
        if (jREntreFechas.isSelected()) {
            java.util.Date fecha1 = jDCIngreso.getDate();
            java.util.Date fecha2 = jDCEgreso.getDate();
            LocalDate fechaComp1 = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaComp2 = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            productos = pd.buscarProductoPorFechas(fechaComp1, fechaComp2);
        }
        borrarFilas();

        for (Producto tabMos : productos) {
            tab.addRow(new Object[]{tabMos.getNombreProducto(),
                tabMos.getDescripcion(), tabMos.getPrecioActual(), tabMos.getStock(),
                tabMos.getStockMinimo(), tabMos.isEstado()});
        }


    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRFechaEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFechaEspecificaActionPerformed
        if (jRFechaEspecifica.isSelected()) {
            jDCEgreso.setEnabled(false);
            jREntreFechas.setSelected(false);
            jDCIngreso.setEnabled(true);
        } else {
            jDCIngreso.setEnabled(false);
            jDCEgreso.setEnabled(false);
        }
    }//GEN-LAST:event_jRFechaEspecificaActionPerformed

    private void jREntreFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREntreFechasActionPerformed
        if (jREntreFechas.isSelected()) {
            jRFechaEspecifica.setSelected(false);
            jDCIngreso.setEnabled(true);
            jDCEgreso.setEnabled(true);
        } else {
            jDCIngreso.setEnabled(false);
            jDCEgreso.setEnabled(false);
        }
    }//GEN-LAST:event_jREntreFechasActionPerformed

    private void borrarFilas() {
        int indice = tab.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            tab.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCEgreso;
    private com.toedter.calendar.JDateChooser jDCIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jREntreFechas;
    private javax.swing.JRadioButton jRFechaEspecifica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
}
